export login from './login.vue'
export main from './main.vue'
export topPoints from './top-points.vue'
export banned from './banned.vue'
export approvePoints from './approve-points.vue'
export strategy from './strategy.vue'
export viewpoints from './viewpoints.vue'
export noteMessages from './note-messages.vue'